### ISSUE TITLE
I need help compiling the project.

### ISSUE THREAD

**Issue by de1r1xxx** [bmorcelli/m5stick-nemo#9]
I tried to compile the project without changes using arduino and got this error: multiple definition of `ieee80211_raw_frame_sanity_check` (this problem only occurred with the 2.5.0 update, everything worked fine in 2.4.1)

I hope you can help me solve this

**Comment by bmorcelli** [comment]
Please read and follow the [DEAUTH Prerequisites](https://github.com/bmorcelli/m5stick-nemo/tree/main/DEAUTH%20Prerequisites)

you can also run of the scripts in the folder to automatically do that.

**Comment by de1r1xxx** [comment]
thx
